#{% set data = load_setup_py_data() %}
{% set version = "4.0.0" %}

package:
  name: mpi4py
  version: {{ version }}

source:
  - git_url: https://github.com/benkirk/derecho-pytorch-mpi.git
    git_rev: 'conda-packaging'

build:
  #script: build.sh

  rpaths:
    - lib/
    - lib64/
    - '/glade/u/apps/common/23.08/spack/opt/spack/cuda/12.2.1/lib64'
    - '/glade/u/apps/derecho/23.09/opt/view/lib'
    - '/glade/u/apps/derecho/23.09/opt/view/lib64'

  runpath_whitelist:
    - '/glade/u/apps/common/23.08/spack/opt/spack/cuda/12.2.1/lib64'
    - '/glade/u/apps/derecho/23.09/opt/view/lib'
    - '/glade/u/apps/derecho/23.09/opt/view/lib64'
    - '/glade/*/lib'
    - '/glade/*/lib64'

  # we're really abusing conda-build here.  This package will only work
  # on Derecho with cray-mpich - therefore it will have many dependent
  # shared libraries outside the conda-build source tree.  That's OK,
  # if distasteful.  Allow it.
  missing_dso_whitelist:
    - '*/libpmi*.so.0'
    - '*/libpals.so.0'
    - '*/libcuda*.so.*'
    - '*/libmpi_*.so*'
    - '*/libpthread.so.0'
    - '/lib64/librt.so.1'
    - '/lib64/libc.so.6'

requirements:
  build:
    - wget
    - curl
    - cython
    - git
    - python
    - pip

  run:
    - python

test:
  imports:
    - mpi4py
    - mpi4py.MPI
    - mpi4py.futures
    - mpi4py.util.dtlib
    - mpi4py.util.pkl5
    - mpi4py.util.pool
    - mpi4py.util.sync

about:
  home: https://mpi4py.github.io/
  license: BSD-3-Clause
  license_family: BSD
  #flicense_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://github.com/mpi4py/mpi4py
