{% set data = load_setup_py_data() %}
{% set version = "2.3.1" %}

package:
  name: pytorch
  version: {{ version }} #{{ data['version'] }}

source:
  - git_url: https://github.com/benkirk/derecho-pytorch-mpi.git
    git_rev: 'conda-packaging'
  # path: ../../config_env.sh
  # path: ../../Makefile
  # path: ../../utils
  #
  # #git_url: https://github.com/pytorch/pytorch
  # #git_rev: v{{ version }}
  # url: https://github.com/pytorch/pytorch/releases/download/v{{ version }}/pytorch-v{{ version }}.tar.gz
  # sha256: 6c66b59345091907cd62a693b647cee224558e7f15a9b04f4f322f4f6ffeb75b
  # folder: pytorch-v{{ version }}


build:
  number: 0
  script: build.sh


requirements:
  build:
    - python=3.11
    - astunparse
    - cmake
    - conda-build
    - cusparselt
    - expecttest!=0.2.0
    - ffmpeg>=4.2.2,<5
    - filelock
    - flake8        # <-- torchvision
    - fsspec
    - hypothesis
    - jinja2
    - lark
    - libjpeg-turbo # <-- torchvision
    - libpng        # <-- torchvision
    - lintrunner
    - pytorch::magma-cuda121 # <-- https://github.com/pytorch/pytorch?tab=readme-ov-file#install-dependencies
    - mypy          # <-- torchvision
    - networkx
    - ninja
    - numpy<2
    - optree>=0.11.0
    - packaging
    - pip
    - psutil
    - pytest        # <-- torchvision
    - pytest-mock   # <-- torchvision
    - pyyaml
    - requests
    - scipy         # <-- torchvision
    - setuptools
    - sympy
    - types-dataclasses
    - typing        # <-- torchvision
    - typing-extensions>=4.8.0

  run:
    - python {{PY_VER}}*

test:
  imports:
    - torch

  requires:
    - pytest >=3.0.0
    - pytest-cov >=2.3.1

  commands:
    - pytest -vv --pyargs torch

about:
  home: data['url']
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD

  summary: data['description']
  description: data['long_description']
  doc_url: https://github.com/benkirk/derecho-pytorch-mpi
  dev_url: data['url']
