# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extended-keys
host_build_env:
  - '{{ environ.get(NCAR_HOST) }}'
  - '{{ environ.get(NCAR_BUILD_ENV) }}'
  - gcc-12.2.0
  - cray-mpich
  - cuda-12

extend_keys:
  - host_build_env
